version: "3"

services:
  flight_api:
    build:
      context: .
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/go/src/

  mongodb:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - "mongodb:/go/data"


volumes:
  mongodb: